server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: hello-service

logging:
  level:
    root: INFO
    com.example.helloworld: DEBUG

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}
